apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
    useBuildkit: true 
  artifacts:
    - image: obiorai/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: "src/**/*.ts"
            src: "src/**/*.ts" 
          - dest: "package*.json"
            src: "package*.json"
    - image: obiorai/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: "src/**/*.ts"
            src: "src/**/*.ts" 
          - dest: "package*.json"
            src: "package*.json"
    - image: obiorai/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: "src/**/*.ts"
            src: "src/**/*.ts" 
          - dest: "package*.json"
            src: "package*.json"
    - image: obiorai/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: "src/**/*.ts"
            src: "src/**/*.ts"
          - dest: "package*.json"
            src: "package*.json"
    - image: obiorai/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: "src/**/*.ts"
            src: "src/**/*.ts"
          - dest: "package*.json"
            src: "package*.json"
    - image: obiorai/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: "**/*.ts"
            src: "src/**/*.ts"
          - dest: "package*.json"
            src: "package*.json"   