name: deploy-tickets

on:
  push:
    branches:
      - main
    paths:
      - 'tickets/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: cd tickets && docker build -t obiorai/tickets .
      - run: docker push obiorai/tickets
